// output/vue/vue3/src/components/countdown/countdown-component.vue
<template>
  <div>
    <div
      class="align-items-center d-flex justify-content-center timeDisplayContainer"
    >
      <span id="timeDisplay">{{ formatTime(currentTime) }}</span>
    </div>
    <div>
      <button class="btn btn-success" @click="start()">Start</button>
      <button class="btn btn-warning" @click="reset()">Reset</button>
      <button class="btn btn-danger" @click="stop()">Stop</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "countdown-component",

  props: ["startTimeCountdown"],

  data() {
    return { timerId: null, startTime: 0, currentTime: 0 };
  },

  mounted() {
    this.startTime = this.startTimeCountdown;
    this.currentTime = this.startTime;
  },

  methods: {
    formatTime(time: number) {
      const minutes = Math.floor(time / 60);
      const seconds = time % 60;
      return `${this.padDigits(minutes)}:${this.padDigits(seconds)}`;
    },
    padDigits(number: number) {
      return number.toString().padStart(2, "0");
    },
    start() {
      if (!this.timerId) {
        if (this.currentTime === 0) {
          this.currentTime = this.startTime;
        }
        this.timerId = setInterval(() => {
          this.currentTime = this.currentTime - 1;
          if (this.currentTime === 0) {
            this.stop();
            alert("Der Countdown ist abgelaufen!");
          }
        }, 1000);
      }
    },
    stop() {
      if (this.timerId) {
        clearInterval(this.timerId);
        this.timerId = null;
      }
    },
    reset() {
      this.stop();
      this.currentTime = this.startTime;
    },
  },
});
</script>

<style scoped>
#timeDisplay {
  font-size: 45px;
}
.timeDisplayContainer {
  margin-top: 40px;
  margin-bottom: 40px;
}
</style>

// output/react/src/components/countdown/countdown-component.jsx
import * as React from "react";
import { useState, useEffect } from "react";

function CountdownComponent(props) {
  const [timerId, setTimerId] = useState(() => null);

  const [startTime, setStartTime] = useState(() => 0);

  const [currentTime, setCurrentTime] = useState(() => 0);

  function formatTime(time) {
    const minutes = Math.floor(time / 60);
    const seconds = time % 60;
    return `${padDigits(minutes)}:${padDigits(seconds)}`;
  }

  function padDigits(number) {
    return number.toString().padStart(2, "0");
  }

  function start() {
    if (!timerId) {
      if (currentTime === 0) {
        setCurrentTime(startTime);
      }
      setTimerId(
        setInterval(() => {
          setCurrentTime(currentTime - 1);
          if (currentTime === 0) {
            stop();
            alert("Der Countdown ist abgelaufen!");
          }
        }, 1000)
      );
    }
  }

  function stop() {
    if (timerId) {
      clearInterval(timerId);
      setTimerId(null);
    }
  }

  function reset() {
    stop();
    setCurrentTime(startTime);
  }

  useEffect(() => {
    setStartTime(props.startTimeCountdown);
    setCurrentTime(startTime);
  }, []);

  return (
    <>
      <div>
        <div className="align-items-center d-flex justify-content-center timeDisplayContainer">
          <span id="timeDisplay">{formatTime(currentTime)}</span>
        </div>

        <div>
          <button className="btn btn-success" onClick={(event) => start()}>
            Start
          </button>

          <button className="btn btn-warning" onClick={(event) => reset()}>
            Reset
          </button>

          <button className="btn btn-danger" onClick={(event) => stop()}>
            Stop
          </button>
        </div>
      </div>
      <style jsx>{`
        #timeDisplay {
          font-size: 45px;
        }
        .timeDisplayContainer {
          margin-top: 40px;
          margin-bottom: 40px;
        }
      `}</style>
    </>
  );
}

export default CountdownComponent;
