// output/vue/vue3/src/components/radio/radio-group-component.vue
<template>
  <fieldset class="radio-button-group">
    <slot />
  </fieldset>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import radioStore from "./radio.context.js";
import { RadioGroupProps } from "./radio.model";

export default defineComponent({
  name: "radio-group",

  props: ["size", "name", "multiple", "callback"],

  provide() {
    const _this = this;
    return {
      [radioStore.key]: {
        size: _this.size,
        name: _this.name,
        multiple: _this.multiple || false,
        selectedValues: new Set(),
        callback: _this.callback,
      },
    };
  },
});
</script>

<style scoped>
.radio-button-group {
  display: flex;
}
</style>

// output/angular/src/components/radio/radio-group-component.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

import radioStore from "./radio.context.js";
import { RadioGroupProps } from "./radio.model";

@Component({
  selector: "radio-group, RadioGroup",
  template: `
    <fieldset class="radio-button-group">
      <ng-content></ng-content>
    </fieldset>
  `,
  styles: [
    `
      .radio-button-group {
        display: flex;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export class RadioGroup {
  @Input() size: RadioGroupProps["size"];
  @Input() name: RadioGroupProps["name"];
  @Input() multiple: RadioGroupProps["multiple"];
  @Input() callback: RadioGroupProps["callback"];
}
