// output/react/src/components/radio/radio-group-component.jsx
import * as React from "react";
import { useContext } from "react";
import radioContext from "./radio.context.js";

function RadioGroup(props) {
  return (
    <>
      <radioContext.Provider
        value={{
          size: props.size,
          name: props.name,
          multiple: props.multiple || false,
          selectedValues: new Set(),
          callback: props.callback,
        }}
      >
        <fieldset className="radio-options-group">{props.children}</fieldset>
      </radioContext.Provider>
      <style jsx>{`
        .radio-options-group {
          display: flex;
        }
      `}</style>
    </>
  );
}

export default RadioGroup;

// output/vue/vue3/src/components/radio/radio-group-component.vue
<template>
  <fieldset class="radio-options-group">
    <slot />
  </fieldset>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import radioContext from "./radio.context.js";
import { RadioGroupProps } from "./radio.model";

export default defineComponent({
  name: "radio-group",

  props: ["size", "name", "multiple", "callback"],

  provide() {
    const _this = this;
    return {
      [radioContext.key]: {
        size: _this.size,
        name: _this.name,
        multiple: _this.multiple || false,
        selectedValues: new Set(),
        callback: _this.callback,
      },
    };
  },
});
</script>

<style scoped>
.radio-options-group {
  display: flex;
}
</style>
