// output/angular/src/components/todo/todo.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

export type TodoProps = {
  todo: TodoType;
};

import todosState from "./todos-state";
import type { Todo as TodoType } from "./todos-state";

@Component({
  selector: "todo, Todo",
  template: `
    <li
      [class]="\`\${todo.completed ? 'completed' : ''} \${editing ? 'editing' : ''}\`"
    >
      <div class="view">
        <input
          class="toggle"
          type="checkbox"
          [attr.checked]="todo.completed"
          (click)="
          toggle();
        "
        />

        <label
          (dblClick)="
          editing = true;
        "
        >
          {{todo.text}}
        </label>

        <button
          class="destroy"
          (click)="
          todosState.todos.splice(todosState.todos.indexOf(todo));
        "
        ></button>
      </div>

      <ng-container *ngIf="editing">
        <input
          class="edit"
          [attr.value]="todo.text"
          (blur)="
          editing = false;
        "
          (keyUp)="
          todo.text = $event.target.value;
        "
        />
      </ng-container>
    </li>
  `,
  standalone: true,
  imports: [CommonModule],
})
export class Todo {
  todosState = todosState;

  @Input() todo: TodoProps["todo"];

  editing = false;
  toggle() {
    const newBool: boolean = !this.todo.completed;
    this.todo.completed = newBool;
  }
}

// output/react/src/components/todo/todo.jsx
import * as React from "react";
import { useState } from "react";
import todosState from "./todos-state";

function Todo(props) {
  const [editing, setEditing] = useState(() => false);

  function toggle() {
    const newBool = !props.todo.completed;
    props.todo.completed = newBool;
  }

  return (
    <li
      className={`${props.todo.completed ? "completed" : ""} ${
        editing ? "editing" : ""
      }`}
    >
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={props.todo.completed}
          onClick={(event) => {
            toggle();
          }}
        />

        <label
          onDblClick={(event) => {
            setEditing(true);
          }}
        >
          {props.todo.text}
        </label>

        <button
          className="destroy"
          onClick={(event) => {
            todosState.todos.splice(todosState.todos.indexOf(props.todo));
          }}
        />
      </div>

      {editing ? (
        <>
          <input
            className="edit"
            value={props.todo.text}
            onBlur={(event) => {
              setEditing(false);
            }}
            onKeyUp={(event) => {
              props.todo.text = event.target.value;
            }}
          />
        </>
      ) : null}
    </li>
  );
}

export default Todo;
