// output/vue/vue3/src/components/todo/todos.vue
<template>
  <section class="main">
    <template v-if="todosState.todos.length">
      <input
        class="toggle-all"
        type="checkbox"
        :checked="todosState.allCompleted"
        @click="
          const newValue = !todosState.allCompleted;
          for (const todoItem of todosState.todos) {
            todoItem.completed = newValue;
          }
        "
      />
    </template>

    <ul class="todo-list">
      <template :key="index" v-for="(todo, index) in todosState.todos">
        <todo :todo="todo"></todo>
      </template>
    </ul>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import todosState from "./todos-state";
import Todo from "./todo.vue";

export type TodosProps = {};

export default defineComponent({
  name: "todos",
  components: { Todo: Todo },

  data() {
    return { todosState };
  },
});
</script>

// output/react/src/components/todo/todos.jsx
import * as React from "react";
import todosState from "./todos-state";
import Todo from "./todo";

function Todos(props) {
  return (
    <section className="main">
      {todosState.todos.length ? (
        <>
          <input
            className="toggle-all"
            type="checkbox"
            checked={todosState.allCompleted}
            onClick={(event) => {
              const newValue = !todosState.allCompleted;
              for (const todoItem of todosState.todos) {
                todoItem.completed = newValue;
              }
            }}
          />
        </>
      ) : null}

      <ul className="todo-list">
        {todosState.todos?.map((todo) => (
          <Todo todo={todo} />
        ))}
      </ul>
    </section>
  );
}

export default Todos;
